# 基本索引与切片的使用

## 索引运算符

- 所以就是`[   ]`，其运算符重载函数：
    - `__getitem__`：获取
    - `__setitem__`：设置
        

- 下面是标准的例子

In [1]:
import torch

t = torch.Tensor(
    [
        [1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0]
    ]
)
t[1]

tensor([4., 5., 6.])

## 切片

- 切片在Python中试一个内置对象，其构造器声明如下：
    -  `slice(stop)`
    -  `slice(start, stop[, step])`
- Tensor的索引运算支持切片的独特语法就是：
    - `:`作为切片的参数分隔符。

### 切片对象

In [7]:
import torch

t = torch.Tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(t[slice(2)])   # 0-2(不包含2)
print(t[slice(0,2, 1)])   # 0-2，步长是1

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### 切片表达式

- 使用`:`来区分三个参数。
- 可以使用默认值：
    - start默认0
    - end默认是长度+1
    - step默认1

In [14]:
import torch

t = torch.Tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(t[2])   # 这个不是切片了，是标准的索引
print(t[:2]) 
print(t[0:2:1])  # 0-2，步长是1
print(t[::])  # 0-2，步长是1

tensor([7., 8., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


### 切片中负数的使用

- 负数表示反方向
    - 负start与负end表示反向的位置；
    - 负step表示反向步长；

In [10]:
import torch

t = torch.Tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(t[1:-1])  # 第二个，到倒数是第一个（最后一个）（不包含倒数第一个）
print(t[-1:0:-1])   # Tensor中不支持负的步长（因为逆序操作的缘故）

tensor([[4., 5., 6.]])


ValueError: negative step not yet supported

# 索引的高级使用

- 在numpy中提供比较多的高级使用，这里在没有足够官方文档的情况先，按照Numpy的功能验证。

## Ellipsis支持

In [16]:
import numpy as np
import torch 
t = torch.Tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
n = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print(n[...])
print(t[...])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [27]:
import numpy as np
import torch 
n = np.array(
    [
        [
            [1],
            [2],
            [3]], 
        [
            [4],
            [5],
            [6]
        ]
    ]
)
print(n[..., 0])   # 维度压缩，最后一维被压缩
t = torch.Tensor(
    [
        [
            [1],
            [2],
            [3]], 
        [
            [4],
            [5],
            [6]
        ]
    ]
)
print(t[..., 0])   # 维度压缩，最后一维被压缩
print(t[:, :, 0])  # 与上面等价

[[1 2 3]
 [4 5 6]]
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 整数数组索引

- 在Numpy支持索引是数组对象。

In [29]:
import numpy as np
import torch 
t = torch.Tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
n = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print(n[[0,1]])
print(t[[0,1]])


[[1 2 3]
 [4 5 6]]
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 多维索引

- 多维索引就是使用逗号分隔维数，而不是使用嵌套方式。

In [32]:
a = [
    [1, 2, 3],
    [4, 5, 6]
]
print(a[0][0])
# print(a[0, 0])   # Python不支持

1


In [35]:
import numpy as np
import torch 
t = torch.Tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
n = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print(n[0,1])
print(t[0,1])

print(n[[0,2], [1]])   # 多维数组风格
print(t[[0,2], [1]])



2
tensor(2.)
[2 8]
tensor([2., 8.])


## 逻辑数组索引

- 就是下标与原来的矩阵完全一样的形状，取值使用对用的逻辑值来决定。

In [40]:
import numpy as np
import torch 
t = torch.Tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
n = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

idx1 = n>5
print(n[idx1])

idx2 = t>5
print(n[idx2])    # 形状shape会改变

[6 7 8 9]
[6 7 8 9]


## 使用索引修改值

- 使用索引可以访问值，值得形状最好与索引对应，某些时候也不需要对应。下面使用一个例子说明，

In [41]:
import torch 
t = torch.Tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

t[t >5] = 88
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5., 88.],
        [88., 88., 88.]])


----